#!/bin/bash

function stop_docker {
  docker stop $1_front &> /dev/null
  docker stop $1_api &> /dev/null
  docker stop $1_db &> /dev/null
  docker rm $1_front &> /dev/null
  docker rm $1_api &> /dev/null
  docker rm $1_db &> /dev/null
}

function start_docker {
  docker-compose up -d --build db
  docker-compose up -d --build api
  docker-compose up -d --build front
}

function change_db_api {
  rm db_scripts/*ddl.sql
  cp dbmovie/$1 db_scripts/
  previous_jdbc=$(head -1 movieapi/application.properties | cut -c2-)
  sed -i "s/$previous_jdbc/$2/g" movieapi/application.properties
}

function change_docker {
  rm docker-compose.yml
  cp conf/docker-$1.yml docker-compose.yml
}

echo 'Il y a 3 alternatives pour votre base de données'
echo 'Sélection        Alternative'
echo '-----------------------------------------------'

if [[ "$( docker container inspect -f '{{.State.Running}}' mariadb_db )" == "true" ]] &> /dev/null
then
  echo ' 1    [*]        MariaDB'
  running_database="mariadb"
else
  echo ' 1    [ ]        MariaDB'
fi
if [[ "$( docker container inspect -f '{{.State.Running}}' postgres_db )" == "true" ]] &> /dev/null
then
  echo ' 2    [*]        PosgreSQL'
  running_database="postgres"
else
  echo ' 2    [ ]        PosgreSQL'
fi
if [[ "$( docker container inspect -f '{{.State.Running}}' mysql_db )" == "true" ]] &> /dev/null
then
  echo ' 3    [*]        MySQL'
  running_database="mysql"
else
  echo ' 3    [ ]        MySQL'
fi

stop_docker "$running_database"
echo 'Appuyez sur Entrée pour conserver la valeur par défaut [*]'
read -p 'ou choisissez le numéro sélectionné : ' database

case "$database" in
	1) echo -e "\nAlternative MariaDB sélectionnée"
     database="mariadb"
     change_db_api "my_cine_ddl.sql" "$database"
     change_docker "$database"
     start_docker ;;
	2) echo -e "\nAlternative PostgreSQL sélectionnée"
     database="postgres"
     change_db_api "pg_cine_ddl.sql" "postgresql"
     change_docker "$database"
     start_docker ;;
	3) echo -e "\nAlternative MySQL sélectionnée"
     database="mysql"
     change_db_api "my_cine_ddl.sql" "$database"
     change_docker "$database"
     start_docker ;;
  *) echo -e "\nAlternative inconnue : $database"
	   exit -1;;
esac
