version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'localhost'
    ports:
      - 80:80
      - 443:443
      - 22:22
    container_name: gitlab
    volumes:
      - ${PWD}/config:/etc/gitlab
      - ${PWD}/logs:/var/log/gitlab
      - ${PWD}/data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      default:
        ipv4_address: 172.20.0.3

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/phbasin/docker/pipeline/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.20.0.2

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
         gateway: 172.20.0.1
