version: "3.3"
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbmovie
      MYSQL_USER: movie
      MYSQL_PASSWORD: password
  api:
    container_name: mysql_api
    build:
      context: ./movieapi
    ports:
      - "8081:8080"
  front:
    container_name: mysql_front
    build:
      context: ./moviefront
    ports:
      - "8082:80"
volumes:
  mysql_volume: {}
